# Generated by Django 4.1.4 on 2023-02-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.TextField(max_length=200, null=True)),
                ('father_name', models.TextField(max_length=200, null=True)),
                ('mother_name', models.TextField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHERS', 'others')], max_length=50, null=True)),
                ('standard', models.TextField(max_length=200, null=True)),
                ('section', models.PositiveBigIntegerField(null=True)),
                ('school_name', models.TextField(max_length=200, null=True)),
                ('date_of_birth', models.DateField()),
                ('admission_no', models.PositiveIntegerField()),
                ('tc_no', models.PositiveIntegerField()),
            ],
        ),
    ]
