# Generated by Django 4.1.4 on 2023-01-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_user_date_joined_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='Category',
            field=models.CharField(choices=[('ELECTRONICS', 'ELECTRONICS'), ('TOYS', 'TOYS'), ('FASHION', 'FASHION'), ('GROCERY', 'GROCERY')], max_length=500),
        ),
    ]
