# Generated by Django 4.1.4 on 2023-01-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productdata_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_user',
        ),
    ]
