# Generated by Django 4.1.4 on 2023-01-15 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_is_staff_user_is_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', related_query_name='customer', to='products.customerdata'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
