# Generated by Django 4.1.4 on 2023-01-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_order_customer_fk_alter_user_is_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdata',
            old_name='User',
            new_name='user',
        ),
    ]
