# Generated by Django 4.1.4 on 2023-01-15 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_user_customerdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_fk',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', related_query_name='customer', to='products.customerdata'),
        ),
    ]
