# Generated by Django 4.1.4 on 2023-01-15 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_customerdata_user_alter_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customer_fk',
        ),
    ]
