# Generated by Django 4.1.4 on 2023-01-15 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_customerdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_fk', related_query_name='customer_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
