# Generated by Django 4.1.4 on 2023-01-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_customerdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='Profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
