# Generated by Django 4.1.4 on 2023-01-18 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_customerdata_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='Profile_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(blank=True, default='SOME STRING', upload_to='pics')),
                ('CreatedDate', models.DateField(auto_now_add=True, null=True)),
                ('author_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
