# Generated by Django 4.1.4 on 2023-01-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_customerdata_profile_pic_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_view_post', 'customer_can_view_post'), ('can_change_post', 'customer_can_change_post'))},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='profile.png', upload_to='pics'),
        ),
    ]
