# Generated by Django 4.1.4 on 2023-02-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_customerdata_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='documents/')),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
